# SPDX-FileCopyrightText: Kevin Stenzel
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render an :class:`~lmnradius.models.Instance` into its two mounted config files.

The control plane writes these into ``render_dir/<name>/`` and bind-mounts that
directory read-only at ``/etc/lmnradius/instance.d`` inside the container, where
the entrypoint ``$-INCLUDE``s them:

* :func:`render_clients_conf` -> ``clients.conf`` (one ``client{}`` per AP subnet);
* :func:`render_ssid_policy` -> ``ssid-policy`` (inner-tunnel post-auth unlang).

Both are PURE functions of their arguments (no I/O, no Docker), so they are
directly unit-testable. Interpolated values are already model-validated, but we
escape them again here as defence in depth: keep the rendered output safe even if
a caller hands us a hand-built model.
"""

from __future__ import annotations

from .models import Instance

_CLIENTS_HEADER = (
    "# Generated by lmnradius — one client{} per AP-management subnet.\n"
    "# The container entrypoint appends the loopback healthcheck client itself.\n"
    "# Do not edit by hand; it is overwritten on every reconcile.\n"
)
_SSID_POLICY_HEADER = (
    "# Generated by lmnradius — per-SSID group gate + optional dynamic VLAN.\n"
    "# Included into sites/inner-tunnel post-auth via $-INCLUDE.\n"
    "# Do not edit by hand; it is overwritten on every reconcile.\n"
)


def _escape_config_string(value: str) -> str:
    """Backslash-escape ``\\`` and ``"`` so ``value`` is safe inside a FreeRADIUS
    double-quoted string. The model regexes already forbid both characters (and
    newlines), so this is defence in depth, not the primary guard."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_clients_conf(inst: Instance, radius_secret: str) -> str:
    """Render ``clients.conf``: one ``client{}`` block per AP-management subnet.

    :param inst: the instance whose ``client_subnets`` become the ``client{}`` blocks.
    :param radius_secret: the AP shared-secret value (already read from its file).
    :returns: the file contents, ending in a newline.
    :raises ValueError: if ``radius_secret`` is empty or contains a newline (which
        would break out of the ``client{}`` block — a config-injection guard).
    """
    if not radius_secret or "\n" in radius_secret or "\r" in radius_secret:
        raise ValueError("radius_secret must be a non-empty single-line value")

    blocks: list[str] = []
    for index, cidr in enumerate(inst.client_subnets, start=1):
        shortname = f"ap-{index}"
        blocks.append(
            f"client {shortname} {{\n"
            f"    ipaddr = {cidr}\n"
            f"    secret = {radius_secret}\n"
            f"    proto = udp\n"
            f"    require_message_authenticator = yes\n"
            f"    shortname = {shortname}\n"
            f"}}\n"
        )
    return _CLIENTS_HEADER + "\n" + "\n".join(blocks)


def render_ssid_policy(inst: Instance) -> str:
    """Render the inner-tunnel post-auth ``ssid-policy`` unlang.

    Emits one branch per SSID, chained with ``if``/``elsif``: if the request's
    SSID matches and the user is in the SSID's ``allowed_group`` it is accepted
    (optionally pinned to a dynamic VLAN); a matching SSID with the wrong group is
    rejected, and a final ``else { reject }`` denies any SSID not served here.

    :param inst: the instance whose ``ssids`` drive the branches (always >= 1).
    :returns: the file contents, ending in a newline.
    """
    lines: list[str] = []
    for index, ssid in enumerate(inst.ssids):
        keyword = "if" if index == 0 else "elsif"
        name = _escape_config_string(ssid.name)
        group = _escape_config_string(ssid.allowed_group)
        lines.append(f'{keyword} (&Called-Station-SSID == "{name}") {{')
        lines.append(f'    if (&LDAP-Group == "{group}") {{')
        if ssid.vlan is not None:
            lines.append("        update reply {")
            lines.append("            &Tunnel-Type := VLAN")
            lines.append("            &Tunnel-Medium-Type := IEEE-802")
            lines.append(f'            &Tunnel-Private-Group-Id := "{ssid.vlan}"')
            lines.append("        }")
        else:
            # In the group, no dynamic VLAN: accept and let the AP's static VLAN
            # apply. 'noop' keeps the block non-empty (radiusd -XC rejects empty
            # sections), matching the shipped default ssid-policy.
            lines.append("        noop")
        lines.append("    }")
        lines.append("    else {")
        lines.append("        reject")
        lines.append("    }")
        lines.append("}")
    # Unknown SSID on this instance -> deny.
    lines.append("else {")
    lines.append("    reject")
    lines.append("}")
    return _SSID_POLICY_HEADER + "\n".join(lines) + "\n"
